version: "2.3"

services:
  app:
    image: jeanblanchard/tomcat:tomcat7-java7
    volumes:
      - ${APP_PATH}:/opt/tomcat/webapps
      - ${APP_CONF_PATH}/server.xml:/opt/tomcat/conf/server.xml
      - /usr/share/fonts/truetype:/usr/share/fonts/truetype
      - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - VIRTUAL_PORT=8080
      - JAVA_OPTS=-DJAVA_ENV=production -Djava.security.egd=file:/dev/./urandom -Duser.timezone=GMT+08 -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote.port=9981 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
      - CATALINA_OPTS=-server -Xms6g -Xmx6g -Xmn4g -Xss1024k -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:CMSFullGCsBeforeCompaction=5 -XX:CMSInitiatingOccupancyFraction=80 -XX:+UseCMSCompactAtFullCollection -XX:+CMSClassUnloadingEnabled -XX:+DisableExplicitGC -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+HeapDumpOnOutOfMemoryError -Xloggc:/var/log/gc.log
    ports:
      - 8877:8877
    external_links:
      - mysql_master_1:mysql.dl.baffedu.com
  # cpu_shares: 2048
  # app_bak:
  #   image: jeanblanchard/tomcat:tomcat7-java7
  #   volumes:
  #     - ${APP_PATH}:/opt/tomcat/webapps
  #     - ${APP_CONF_PATH}/server.xml:/opt/tomcat/conf/server.xml
  #     - /usr/share/fonts/truetype:/usr/share/fonts/truetype
  #     - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg
  #   environment:
  #     - VIRTUAL_HOST=${APP_HOST}
  #     - VIRTUAL_PORT=8080
  #     - JAVA_OPTS=-DJAVA_ENV=production -Duser.timezone=GMT+08 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom
  #     - CATALINA_OPTS=-server -Xms1024m -Xmx2048m -Xss1024K -XX:PermSize=512m -XX:MaxPermSize=1024m
  #   external_links:
  #     - mysql_master_1:mysql.dl.baffedu.com
  #   cpu_shares: 2048
  upload:
    image: nginx:1.15-alpine
    volumes:
      - ${UPLOAD_PATH}:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${UPLOAD_HOST}

# when telnet other service, you may need to configure firewalld
# docker network create --driver=bridge --subnet=10.50.0.0/16 baffedu
networks:
  default:
    external:
      name: baffedu