version: "3.3"

services:
  app:
    image: tomcat:7.0-alpine
    volumes:
      - ${APP_PATH}:/usr/local/tomcat/webapps
      - ${APP_CONF_PATH}/server.xml:/usr/local/tomcat/conf/server.xml
      - /usr/share/fonts/truetype:/usr/share/fonts/truetype
      - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - VIRTUAL_PORT=8080
      - JAVA_OPTS=-server -Xms1024m -Xmx2048m -Xss1024K -XX:PermSize=512m -XX:MaxPermSize=1024m -DJAVA_ENV=production
    ports:
      - 8877:8877
    external_links:
      - mysql_master_1:mysql.dl.baffedu.com

# when telnet other service, you may need to configure firewalld
# docker network create --driver=bridge --subnet=10.50.0.0/16 baffedu
networks:
  default:
    external:
      name: baffedu